function plot_my_band(chi,pitch,ffactor,k_plane,Nsearch,Nplot,N, Nth_band, ...
                        search_re,search_im, ...
                        search_re_width,search_im_width, ...
                        search_re_N,search_im_N)


[w_re,w_im] = find_band(chi, pitch, ffactor, k_plane, Nsearch, ...
                                        search_re, search_im, ...
                                        search_re_width, search_im_width, ...
                                        search_re_N, search_im_N);

M = Chi_matrix(chi, pitch, ffactor, k_plane, w_re, w_im, N);

vec = get_one_eig_vec(M, 2*N+1);

plot_fourier_terms(vec,N,pitch,k_plane,Nplot);